stages:
    - build
    - test
    - deploy
    - post deploy

variables:
    APP_BASE_URL: http://jyotishmoy-20011121.s3-website-us-east-1.amazonaws.com
build website:
    image: node:22-alpine
    stage: build
    script:
        - yarn install
        - yarn lint
        - yarn test
        - yarn build
    artifacts: 
        paths: 
            - build

test website:
    image: node:22-alpine
    stage: test
    script: 
        # - test -f build/index.html
        - yarn global add serve
        - apk add curl
        #fixing the error to stop the server to run forever
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"

deploy to s3:
    stage: deploy
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script:
        - aws --version
        - echo $CI_COMMIT_REF_NAME 
        - echo $CI_DEFAULT_BRANCH
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete

production tests:
    stage: post deploy
    image: curlimages/curl:8.10.1
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script: 
        - curl $APP_BASE_URL | grep "React App"

