stages:
    - build
    - test
    - deploy
build website:
    image: node:22-alpine
    stage: build
    script:
        - yarn install
        - yarn lint
        - yarn test
        - yarn build
    artifacts: 
        paths: 
            - build

test website:
    image: node:22-alpine
    stage: test
    script: 
        # - test -f build/index.html
        - yarn global add serve
        - apk add curl
        #fixing the error to stop the server to run forever
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"

deploy to s3:
    stage: deploy
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    script:
        - aws --version
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete
